ALTER TABLE "seller_application" ADD COLUMN "application_number" text;--> statement-breakpoint
ALTER TABLE "seller_application" ADD COLUMN "profile_photo_url" text;--> statement-breakpoint
ALTER TABLE "seller_application" ADD COLUMN "email" text;--> statement-breakpoint
ALTER TABLE "seller_application" ADD COLUMN "date_of_birth" text;--> statement-breakpoint
ALTER TABLE "seller_application" ADD COLUMN "gender" text;--> statement-breakpoint
ALTER TABLE "seller_application" ADD COLUMN "personal_address" text;--> statement-breakpoint
ALTER TABLE "seller_application" ADD COLUMN "personal_latitude" text;--> statement-breakpoint
ALTER TABLE "seller_application" ADD COLUMN "personal_longitude" text;--> statement-breakpoint
ALTER TABLE "seller_application" ADD COLUMN "personal_area" text;--> statement-breakpoint
ALTER TABLE "seller_application" ADD COLUMN "personal_district" text;--> statement-breakpoint
ALTER TABLE "seller_application" ADD COLUMN "personal_division" text;--> statement-breakpoint
ALTER TABLE "seller_application" ADD COLUMN "personal_post_code" text;--> statement-breakpoint
ALTER TABLE "seller_application" ADD COLUMN "business_nature" text;--> statement-breakpoint
ALTER TABLE "seller_application" ADD COLUMN "product_type_id" integer;--> statement-breakpoint
ALTER TABLE "seller_application" ADD COLUMN "bin_number" text;--> statement-breakpoint
ALTER TABLE "seller_application" ADD COLUMN "tin_number" text;--> statement-breakpoint
ALTER TABLE "seller_application" ADD COLUMN "document_urls" json;--> statement-breakpoint
ALTER TABLE "seller_application" ADD COLUMN "bank_name" text;--> statement-breakpoint
ALTER TABLE "seller_application" ADD COLUMN "bank_account_name" text;--> statement-breakpoint
ALTER TABLE "seller_application" ADD COLUMN "bank_account_number" text;--> statement-breakpoint
ALTER TABLE "seller_application" ADD COLUMN "referral_id" text;--> statement-breakpoint
ALTER TABLE "seller_application" ADD COLUMN "referral_name" text;--> statement-breakpoint
ALTER TABLE "seller_application" ADD COLUMN "referral_phone" text;--> statement-breakpoint
ALTER TABLE "seller_application" ADD COLUMN "facebook_url" text;--> statement-breakpoint
ALTER TABLE "seller_application" ADD COLUMN "whatsapp_number" text;--> statement-breakpoint
ALTER TABLE "seller_application" ADD COLUMN "instagram_url" text;--> statement-breakpoint
ALTER TABLE "seller_application" ADD COLUMN "website_url" text;--> statement-breakpoint
ALTER TABLE "seller_application" ADD COLUMN "tiktok_url" text;--> statement-breakpoint
ALTER TABLE "seller_application" ADD COLUMN "twitter_url" text;--> statement-breakpoint
ALTER TABLE "warehouse_application" ADD COLUMN "application_number" text;--> statement-breakpoint
ALTER TABLE "warehouse_application" ADD COLUMN "profile_photo_url" text;--> statement-breakpoint
ALTER TABLE "warehouse_application" ADD COLUMN "email" text;--> statement-breakpoint
ALTER TABLE "warehouse_application" ADD COLUMN "date_of_birth" text;--> statement-breakpoint
ALTER TABLE "warehouse_application" ADD COLUMN "gender" text;--> statement-breakpoint
ALTER TABLE "warehouse_application" ADD COLUMN "personal_address" text;--> statement-breakpoint
ALTER TABLE "warehouse_application" ADD COLUMN "personal_latitude" text;--> statement-breakpoint
ALTER TABLE "warehouse_application" ADD COLUMN "personal_longitude" text;--> statement-breakpoint
ALTER TABLE "warehouse_application" ADD COLUMN "personal_area" text;--> statement-breakpoint
ALTER TABLE "warehouse_application" ADD COLUMN "personal_district" text;--> statement-breakpoint
ALTER TABLE "warehouse_application" ADD COLUMN "personal_division" text;--> statement-breakpoint
ALTER TABLE "warehouse_application" ADD COLUMN "personal_post_code" text;--> statement-breakpoint
ALTER TABLE "warehouse_application" ADD COLUMN "business_nature" text;--> statement-breakpoint
ALTER TABLE "warehouse_application" ADD COLUMN "product_type_id" integer;--> statement-breakpoint
ALTER TABLE "warehouse_application" ADD COLUMN "bin_number" text;--> statement-breakpoint
ALTER TABLE "warehouse_application" ADD COLUMN "tin_number" text;--> statement-breakpoint
ALTER TABLE "warehouse_application" ADD COLUMN "document_urls" json;--> statement-breakpoint
ALTER TABLE "warehouse_application" ADD COLUMN "bank_name" text;--> statement-breakpoint
ALTER TABLE "warehouse_application" ADD COLUMN "bank_account_name" text;--> statement-breakpoint
ALTER TABLE "warehouse_application" ADD COLUMN "bank_account_number" text;--> statement-breakpoint
ALTER TABLE "warehouse_application" ADD COLUMN "referral_id" text;--> statement-breakpoint
ALTER TABLE "warehouse_application" ADD COLUMN "referral_name" text;--> statement-breakpoint
ALTER TABLE "warehouse_application" ADD COLUMN "referral_phone" text;--> statement-breakpoint
ALTER TABLE "warehouse_application" ADD COLUMN "facebook_url" text;--> statement-breakpoint
ALTER TABLE "warehouse_application" ADD COLUMN "whatsapp_number" text;--> statement-breakpoint
ALTER TABLE "warehouse_application" ADD COLUMN "instagram_url" text;--> statement-breakpoint
ALTER TABLE "warehouse_application" ADD COLUMN "website_url" text;--> statement-breakpoint
ALTER TABLE "warehouse_application" ADD COLUMN "tiktok_url" text;--> statement-breakpoint
ALTER TABLE "warehouse_application" ADD COLUMN "twitter_url" text;--> statement-breakpoint
ALTER TABLE "seller_application" ADD CONSTRAINT "seller_application_product_type_id_product_type_id_fk" FOREIGN KEY ("product_type_id") REFERENCES "public"."product_type"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "warehouse_application" ADD CONSTRAINT "warehouse_application_product_type_id_product_type_id_fk" FOREIGN KEY ("product_type_id") REFERENCES "public"."product_type"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "seller_application_number_idx" ON "seller_application" USING btree ("application_number");--> statement-breakpoint
CREATE UNIQUE INDEX "warehouse_application_number_idx" ON "warehouse_application" USING btree ("application_number");