export const dynamic = "force-dynamic";

import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import "./globals.css";
import Providers from "@/app/providers";
import React from "react";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  auth,
}: Readonly<{
  children: React.ReactNode;
  auth: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script dangerouslySetInnerHTML={{__html: `
          window.onerror = function(msg, url, line, col, error) {
            document.body.innerHTML = '<div style="background:red;color:white;font-size:24px;padding:20px;z-index:99999;position:fixed;top:0;left:0;right:0;bottom:0;">GLOBAL ERROR: ' + msg + '<br/>' + url + ':' + line + ':' + col + '<br/><pre>' + (error && error.stack ? error.stack : '') + '</pre></div>';
          };
          window.addEventListener('unhandledrejection', function(event) {
            document.body.innerHTML = '<div style="background:red;color:white;font-size:24px;padding:20px;z-index:99999;position:fixed;top:0;left:0;right:0;bottom:0;">UNHANDLED PROMISE REJECTION: ' + event.reason + '</div>';
          });
        `}} />
      </head>
      <body
        className={`${poppins.variable} font-(family-name:--font-poppins) antialiased`}
        suppressHydrationWarning
      >

        <NuqsAdapter>
          <Providers>
            {children}
            {auth}
          </Providers>
        </NuqsAdapter>
      </body>
    </html>
  );
}
