import { type SQL, sql } from "drizzle-orm";

// Bilingual administrative names are aliases, not a list of displayed locations.
// Only locations present in approved business registrations are returned.
const locationNames = [
  ["Dhaka", "ঢাকা"],
  ["Faridpur", "ফরিদপুর"],
  ["Gazipur", "গাজীপুর"],
  ["Gopalganj", "গোপালগঞ্জ"],
  ["Kishoreganj", "কিশোরগঞ্জ"],
  ["Madaripur", "মাদারীপুর"],
  ["Manikganj", "মানিকগঞ্জ"],
  ["Munshiganj", "মুন্সিগঞ্জ", "মুন্সীগঞ্জ"],
  ["Narayanganj", "নারায়ণগঞ্জ", "নারায়ণগঞ্জ"],
  ["Narsingdi", "নরসিংদী"],
  ["Rajbari", "রাজবাড়ী", "রাজবাড়ী"],
  ["Shariatpur", "শরীয়তপুর", "শরীয়তপুর"],
  ["Tangail", "টাঙ্গাইল"],
  ["Chattogram", "চট্টগ্রাম", "Chittagong"],
  ["Bandarban", "বান্দরবান"],
  ["Brahmanbaria", "ব্রাহ্মণবাড়িয়া", "ব্রাহ্মণবাড়িয়া"],
  ["Chandpur", "চাঁদপুর"],
  ["Cox's Bazar", "কক্সবাজার", "Coxs Bazar"],
  ["Cumilla", "কুমিল্লা", "Comilla"],
  ["Feni", "ফেনী"],
  ["Khagrachhari", "খাগড়াছড়ি", "খাগড়াছড়ি"],
  ["Lakshmipur", "লক্ষ্মীপুর"],
  ["Noakhali", "নোয়াখালী", "নোয়াখালী"],
  ["Rangamati", "রাঙ্গামাটি"],
  ["Barishal", "বরিশাল", "Barisal"],
  ["Barguna", "বরগুনা"],
  ["Bhola", "ভোলা"],
  ["Jhalokati", "ঝালকাঠি"],
  ["Patuakhali", "পটুয়াখালী", "পটুয়াখালী"],
  ["Pirojpur", "পিরোজপুর"],
  ["Khulna", "খুলনা"],
  ["Bagerhat", "বাগেরহাট"],
  ["Chuadanga", "চুয়াডাঙ্গা", "চুয়াডাঙ্গা"],
  ["Jashore", "যশোর", "Jessore"],
  ["Jhenaidah", "ঝিনাইদহ"],
  ["Kushtia", "কুষ্টিয়া", "কুষ্টিয়া"],
  ["Magura", "মাগুরা"],
  ["Meherpur", "মেহেরপুর"],
  ["Narail", "নড়াইল", "নড়াইল"],
  ["Satkhira", "সাতক্ষীরা"],
  ["Mymensingh", "ময়মনসিংহ", "ময়মনসিংহ"],
  ["Jamalpur", "জামালপুর"],
  ["Netrokona", "নেত্রকোণা", "নেত্রকোনা"],
  ["Sherpur", "শেরপুর"],
  ["Rajshahi", "রাজশাহী"],
  ["Bogura", "বগুড়া", "বগুড়া", "Bogra"],
  ["Chapainawabganj", "চাঁপাইনবাবগঞ্জ"],
  ["Joypurhat", "জয়পুরহাট", "জয়পুরহাট"],
  ["Naogaon", "নওগাঁ"],
  ["Natore", "নাটোর"],
  ["Pabna", "পাবনা"],
  ["Sirajganj", "সিরাজগঞ্জ"],
  ["Rangpur", "রংপুর"],
  ["Dinajpur", "দিনাজপুর"],
  ["Gaibandha", "গাইবান্ধা"],
  ["Kurigram", "কুড়িগ্রাম", "কুড়িগ্রাম"],
  ["Lalmonirhat", "লালমনিরহাট"],
  ["Nilphamari", "নীলফামারী"],
  ["Panchagarh", "পঞ্চগড়", "পঞ্চগড়"],
  ["Thakurgaon", "ঠাকুরগাঁও"],
  ["Sylhet", "সিলেট"],
  ["Habiganj", "হবিগঞ্জ"],
  ["Moulvibazar", "মৌলভীবাজার"],
  ["Sunamganj", "সুনামগঞ্জ"],
] as const;

export function canonicalBusinessLocation(value: SQL) {
  const branches = locationNames.flatMap(([canonical, ...aliases]) =>
    [canonical, ...aliases].map(
      (alias) => sql`when ${alias.toLowerCase()} then ${canonical}`,
    ),
  );
  return sql`case lower(regexp_replace(trim(${value}), '( district| division| জেলা| বিভাগ)$', '', 'i'))
    ${sql.join(branches, sql` `)} else ${value} end`;
}
